<?php
declare(strict_types=1);
/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<template x-if="fee.input_type === 'drop_down'">
    <div class="mt-6">
        <div class="mb-4 font-semibold">
            <span x-text="fee.title"></span>
            <span class="text-red-400" x-show="fee.is_required">*</span>
        </div>
        <div class="mb-4" x-show="fee.description.lenght > 0">
            <p x-text="fee.description"></p>
        </div>
        <select class="w-full" x-model="fee.checkedOption" @change="onChangeOption()">
            <template x-for="option in fee.options" :key="option.id">
                <option :value="option.id" x-text="option.field_label"
                        :selected="option.id === fee.checkedOption"></option>
            </template>
        </select>
        <template x-if="fee.is_enabled_customer_message">
            <div class="mt-4">
                <label x-text="fee.customer_message_title"></label>
                <template x-if="fee.customer_message_title.length === 0">
                    <div>
                        <?= /* @noEscape */ __('Message for'); ?> "<span x-text="fee.title"></span>"
                    </div>
                </template>
                <textarea class="w-full" x-model="fee.customerMessage" @change="onChangeOption()"></textarea>
            </div>
        </template>
        <template x-if="fee.is_enabled_date_field">
            <div class="mt-4">
                <label x-text="fee.date_field_title"></label>
                <template x-if="fee.date_field_title.length === 0">
                    <div>
                        <?= /* @noEscape */ __('Date for'); ?> "<span x-text="fee.title"></span>"
                    </div>
                </template>
                <input x-model="fee.dateField" type="date" @change="fee.convertDate()"/>
            </div>
        </template>
    </div>
</template>
