<?php
declare(strict_types=1);
/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<template x-if="fee.input_type === 'hidden'">
    <div class="border-2 p-4 mt-4">
        <div class="mb-4">
            <span class="font-semibold" x-text="fee.title"></span>
            <span class="font-semibold text-red-400" x-show="fee.is_required">*</span>
            <span class="ml-2" x-text="fee.option.field_label"></span>
        </div>
        <div x-show="fee.description.length > 0">
            <p x-text="fee.description"></p>
        </div>
    </div>
</template>
